/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.58
 * Generated at: 2020-10-21 14:08:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.mdoubleh.www.common.LoginManager;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.mdoubleh.www.common.LoginManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	LoginManager lm = LoginManager.getInstance();
	String id = lm.getMemberId(session);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/navbar.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/index.css\" />\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"/images/Logo.png\" />\r\n");
      out.write("<script src=\"/js/category.js\" defer></script>\r\n");
      out.write("<script src=\"/js/moreBtn.js\" defer></script>\r\n");
      out.write("<script src=\"/js/eventFadeIn.js\" defer></script>\r\n");
      out.write("<script src=\"/js/newFadeIn.js\" defer></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Login -->\r\n");
      out.write("\t<div id=\"login\">\r\n");
      out.write("\t\t");

			if (id == null) {
		
      out.write("\r\n");
      out.write("\t\t<span class=\"login__btn\"><a href=\"/login.do\">Login</a></span> \r\n");
      out.write("\t\t");

			} else {
		
      out.write("\r\n");
      out.write("\t\t<span class=\"login__btn\"><a href=\"/logout.do\">Logout</a></span> \r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Navbar -->\r\n");
      out.write("\t<div id=\"navbar\">\r\n");
      out.write("\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t<div class=\"logo__title\">\r\n");
      out.write("\t\t\t\t<a href=\"/\">HESSDALEN</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"square__point\">\r\n");
      out.write("\t\t\t\t<div class=\"squareA\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-square-full\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"squareB\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-square-full\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"menu__list\">\r\n");
      out.write("\t\t\t\t<li class=\"menu__items\"><a href=\"info/info.html\">INFO</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"menu__items\"><a href=\"products/products.html\">PRODUCTS</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"menu__items\"><a href=\"/list.do?pn=1\">SERVICE</a></li>\r\n");
      out.write("\t\t\t\t<form id=\"input__form\" action=''>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" placeholder=\"Search\" id=\"search__input\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-search\"></i>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"category\">\r\n");
      out.write("\t\t\t<i class=\"fas fa-bars\"></i>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"category__click\">\r\n");
      out.write("\t\t<!-- MainBanner -->\r\n");
      out.write("\t\t<div id=\"main__banner\">\r\n");
      out.write("\t\t\t<img src=\"/images/furnitureMain.jpg\" alt=\"MainBanner\">\r\n");
      out.write("\t\t\t<div class=\"main__title\">\r\n");
      out.write("\t\t\t\t<h1>Luxury Furniture</h1>\r\n");
      out.write("\t\t\t\t<h2>\r\n");
      out.write("\t\t\t\t\tFurniture containing both the sensibilty and<br /> comfort of\r\n");
      out.write("\t\t\t\t\tNorthern Europe.\r\n");
      out.write("\t\t\t\t</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"more__btn\">\r\n");
      out.write("\t\t\t\t<p data-link=\"#event__furnture\">More</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Event Furniture -->\r\n");
      out.write("\t\t<div id=\"event__furnture\">\r\n");
      out.write("\t\t\t<div class=\"event__left\">\r\n");
      out.write("\t\t\t\t<div class=\"left__furnture\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/furnitureEvent1.png\" alt=\"event__furniture1\" />\r\n");
      out.write("\t\t\t\t\t<div class=\"left__pricetag\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Lizzio Open-type sofa table</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"pricetag\">\r\n");
      out.write("\t\t\t\t\t\t<p>120$</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"sail__pricetag\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>140$</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"event__tag\">Event</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"event__right\">\r\n");
      out.write("\t\t\t\t<div class=\"event__title\">\r\n");
      out.write("\t\t\t\t\t<div class=\"left__title\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Event Fu</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"right__title\">\r\n");
      out.write("\t\t\t\t\t\t<h2>rniture</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"right__slide\">\r\n");
      out.write("\t\t\t\t\t<div class=\"right__furnitureF\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/images/furnitureEvent2.png\" alt=\"furnitureEventFirst\" />\r\n");
      out.write("\t\t\t\t\t\t<h2>Banson Steel Folding Table 400 A Type</h2>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pricetag\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>450$</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"sail__pricetag\">480$</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"event__tag\">Event</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"right__furnitureS\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/images/furnitureEvent3.png\" alt=\"furnitureEventSeconde\" />\r\n");
      out.write("\t\t\t\t\t\t<h2>Zippo Gray Storage sofa table 1000</h2>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pricetag\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>99$</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"sail__pricetag\">120$</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"event__tag\">Event</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- vertical Bar -->\r\n");
      out.write("\t\t<div id=\"vertical__bar\">\r\n");
      out.write("\t\t\t<div class=\"bar\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- MD Recommendation -->\r\n");
      out.write("\t\t<div id=\"recommendation\">\r\n");
      out.write("\t\t\t<div class=\"recommendation__title\">\r\n");
      out.write("\t\t\t\t<h1>MD Recommendation</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"recommendation__conitainer\">\r\n");
      out.write("\t\t\t\t<div class=\"recommendation__box\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/furnitureMd1.png\" alt=\"furnitureMd\">\r\n");
      out.write("\t\t\t\t\t<h1>Market Bee BENKU Single Corner Sofa Rubber</h1>\r\n");
      out.write("\t\t\t\t\t<div class=\"pricetag\">120$</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"recommendation__box\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/furnitureMd2.png\" alt=\"furnitureMd\">\r\n");
      out.write("\t\t\t\t\t<h1>Bianth Kellen Aqua</h1>\r\n");
      out.write("\t\t\t\t\t<div class=\"pricetag\">325$</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"recommendation__box\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/furnitureMd3.png\" alt=\"furnitureMd\">\r\n");
      out.write("\t\t\t\t\t<h1>Paroma Plane LED Multi-Recipient PU Bed</h1>\r\n");
      out.write("\t\t\t\t\t<div class=\"pricetag\">712$</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Advertising banner -->\r\n");
      out.write("\t\t<div class=\"advertising__banner\">\r\n");
      out.write("\t\t\t<div class=\"banner\">\r\n");
      out.write("\t\t\t\t<img src=\"/images/furnitureBannar.png\" alt=\"advertisingBanner\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- New Furniture -->\r\n");
      out.write("\t\t<div id=\"new__furniture\">\r\n");
      out.write("\t\t\t<div class=\"new__title\">\r\n");
      out.write("\t\t\t\t<div class=\"left__new\">\r\n");
      out.write("\t\t\t\t\t<h2>New Fu</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"right__new\">\r\n");
      out.write("\t\t\t\t\t<h2>rniture</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"new__container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"new__boxf\">\r\n");
      out.write("\t\t\t\t<img src=\"/images/furnitureNewItem1.png\" alt=\"furniturNewItemFirst\">\r\n");
      out.write("\t\t\t\t<div class=\"new__pricetag\">\r\n");
      out.write("\t\t\t\t\t<h1>Odin Living Dining sofa set</h1>\r\n");
      out.write("\t\t\t\t\t<div class=\"pricetag\">240$</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"new__boxc\">\r\n");
      out.write("\t\t\t\t<div class=\"top__box\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/furnitureNewItem2.png\" alt=\"furniturNewItemTop\">\r\n");
      out.write("\t\t\t\t\t<div class=\"new__pricetag\">\r\n");
      out.write("\t\t\t\t\t\t<h1>Ikea LINNMON/ADILS Table</h1>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pricetag\">130$</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"bottom__box\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/furnitureNewItem3.png\"\r\n");
      out.write("\t\t\t\t\t\talt=\"furniturNewItemBottom\">\r\n");
      out.write("\t\t\t\t\t<div class=\"new__pricetag\">\r\n");
      out.write("\t\t\t\t\t\t<h1>round folding table</h1>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pricetag\">175$</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"new__boxs\">\r\n");
      out.write("\t\t\t\t<img src=\"/images/furnitureNewItem4.png\" alt=\"furniturNewItemSecond\">\r\n");
      out.write("\t\t\t\t<div class=\"new__pricetag\">\r\n");
      out.write("\t\t\t\t\t<h1>Ldlab Amazing Wooden Rack MS</h1>\r\n");
      out.write("\t\t\t\t\t<div class=\"pricetag\">680$</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Footer -->\r\n");
      out.write("\t\t<div id=\"footer\">\r\n");
      out.write("\t\t\t<img src=\"/images/tempFooter.png\" alt=\"\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Click Category </div> !! -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
